### ISSUE TITLE
Declaration-rgpd: yarn test 5 failures

### ISSUE THREAD

**Issue by tristanrobert** [SocialGouv/dashlord-actions#222]
```shell
yarn test
yarn run v1.22.19
$ jest

(node:4175) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/4175/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/4175/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/4175/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4175) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:4337) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/4337/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/4337/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/4337/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4337) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4337) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:4541) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/4541/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/4541/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/4541/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4541) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4541) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:4745) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/4745/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/4745/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/4745/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:4950) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/4950/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/4950/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/4950/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4950) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:5154) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/5154/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/5154/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/5154/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:5457) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/5457/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/5457/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/5457/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:5661) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/5661/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/5661/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/5661/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5661) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:5865) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/5865/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/5865/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/5865/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5865) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:6069) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/tristanrobert/.npm/_npx/6069/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/tristanrobert/.npm/_npx/6069/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/home/tristanrobert/.npm/_npx/6069/lib/node_modules/@socialgouv/get-html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL  __test__/analyseFile.test.js (217.1 s)
  ✕ ressourcerie: should return ml and pc (46005 ms)
  ✕ egapro: should return ml and pc (42140 ms)
  ✕ 1000jours-blues: should return ml and pc (43227 ms)
  ✕ should return ml and pc and thirdparties data (42634 ms)
  ✓ should not detect ml nor pc (21 ms)
  ✓ should detect ml : mentions légales (21020 ms)
  ✕ should detect pc : Données personnelles (21227 ms)

  ● ressourcerie: should return ml and pc

    expect(received).toMatchSnapshot()

    Snapshot name: `ressourcerie: should return ml and pc 1`

    - Snapshot  -  4
    + Received  + 14

    @@ -2,19 +2,29 @@
        Object {
          "declarationUrl": "https://ressourcerie.fabrique.social.gouv.fr/mentions-legales",
          "maxScore": 4,
          "mention": "Mentions légales",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "directeur (ou) directrice",
    +       "publication",
    +       "hébergeur (ou) hébergement",
    +       "éditeur (ou) édité par (ou) editeur (ou) edité par",
    +     ],
    +     "score": 0,
          "slug": "ml",
        },
        Object {
          "declarationUrl": "https://ressourcerie.fabrique.social.gouv.fr/politique-confidentialite",
          "maxScore": 4,
          "mention": "Politique de confidentialité",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "@",
    +       "finalité",
    +       "durée de conservation",
    +       "sous-traitants (ou) sous traitants",
    +     ],
    +     "score": 0,
          "slug": "pc",
        },
      ]

       7 |     url: "https://ressourcerie.fabrique.social.gouv.fr",
       8 |   });
    >  9 |   expect(output).toMatchSnapshot();
         |                  ^
      10 | });
      11 |
      12 | test("egapro: should return ml and pc", async () => {

      at Object.toMatchSnapshot (__test__/analyseFile.test.js:9:18)

  ● egapro: should return ml and pc

    expect(received).toMatchSnapshot()

    Snapshot name: `egapro: should return ml and pc 1`

    - Snapshot  -  4
    + Received  + 14

    @@ -2,19 +2,29 @@
        Object {
          "declarationUrl": "https://index-egapro.travail.gouv.fr/mentions-legales",
          "maxScore": 4,
          "mention": "Mentions légales",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "directeur (ou) directrice",
    +       "publication",
    +       "hébergeur (ou) hébergement",
    +       "éditeur (ou) édité par (ou) editeur (ou) edité par",
    +     ],
    +     "score": 0,
          "slug": "ml",
        },
        Object {
          "declarationUrl": "https://index-egapro.travail.gouv.fr/politique-confidentialite",
          "maxScore": 4,
          "mention": "Politique de confidentialité",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "@",
    +       "finalité",
    +       "durée de conservation",
    +       "sous-traitants (ou) sous traitants",
    +     ],
    +     "score": 0,
          "slug": "pc",
        },
      ]

      14 |     url: "https://index-egapro.travail.gouv.fr",
      15 |   });
    > 16 |   expect(output).toMatchSnapshot();
         |                  ^
      17 | });
      18 |
      19 | test("1000jours-blues: should return ml and pc", async () => {

      at Object.toMatchSnapshot (__test__/analyseFile.test.js:16:18)

  ● 1000jours-blues: should return ml and pc

    expect(received).toMatchSnapshot()

    Snapshot name: `1000jours-blues: should return ml and pc 1`

    - Snapshot  -  4
    + Received  + 14

    @@ -2,19 +2,29 @@
        Object {
          "declarationUrl": "https://1000jours-blues.fabrique.social.gouv.fr/mentions-legales",
          "maxScore": 4,
          "mention": "Mentions légales",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "directeur (ou) directrice",
    +       "publication",
    +       "hébergeur (ou) hébergement",
    +       "éditeur (ou) édité par (ou) editeur (ou) edité par",
    +     ],
    +     "score": 0,
          "slug": "ml",
        },
        Object {
          "declarationUrl": "https://1000jours-blues.fabrique.social.gouv.fr/politique-confidentialite",
          "maxScore": 4,
          "mention": "Politique de confidentialité",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "@",
    +       "finalité",
    +       "durée de conservation",
    +       "sous-traitants (ou) sous traitants",
    +     ],
    +     "score": 0,
          "slug": "pc",
        },
      ]

      21 |     url: "https://1000jours-blues.fabrique.social.gouv.fr",
      22 |   });
    > 23 |   expect(output).toMatchSnapshot();
         |                  ^
      24 | });
      25 |
      26 | test("should return ml and pc and thirdparties data", async () => {

      at Object.toMatchSnapshot (__test__/analyseFile.test.js:23:18)

  ● should return ml and pc and thirdparties data

    expect(received).toMatchSnapshot()

    Snapshot name: `should return ml and pc and thirdparties data 1`

    - Snapshot  -  4
    + Received  + 14

    @@ -2,21 +2,31 @@
        Object {
          "declarationUrl": "https://ressourcerie.fabrique.social.gouv.fr/mentions-legales",
          "maxScore": 4,
          "mention": "Mentions légales",
          "missingTrackers": Array [],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "missingWords": Array [
    +       "directeur (ou) directrice",
    +       "publication",
    +       "hébergeur (ou) hébergement",
    +       "éditeur (ou) édité par (ou) editeur (ou) edité par",
    +     ],
    +     "score": 0,
          "slug": "ml",
        },
        Object {
          "declarationUrl": "https://ressourcerie.fabrique.social.gouv.fr/politique-confidentialite",
          "maxScore": 5,
          "mention": "Politique de confidentialité",
          "missingTrackers": Array [
            "jQuery",
    +     ],
    +     "missingWords": Array [
    +       "@",
    +       "finalité",
    +       "durée de conservation",
    +       "sous-traitants (ou) sous traitants",
          ],
    -     "missingWords": Array [],
    -     "score": 4,
    +     "score": 0,
          "slug": "pc",
        },
      ]

      32 |     url: "https://ressourcerie.fabrique.social.gouv.fr",
      33 |   });
    > 34 |   expect(output).toMatchSnapshot();
         |                  ^
      35 | });
      36 |  
      37 |

      at Object.toMatchSnapshot (__test__/analyseFile.test.js:34:18)

  ● should detect pc : Données personnelles

    expect(received).toMatchSnapshot()

    Snapshot name: `should detect pc : Données personnelles 1`

    - Snapshot  - 1
    + Received  + 2

    @@ -11,13 +11,14 @@
          "declarationUrl": "https://ressourcerie.fabrique.social.gouv.fr/some",
          "maxScore": 4,
          "mention": "Données personnelles",
          "missingTrackers": Array [],
          "missingWords": Array [
    +       "@",
            "finalité",
            "durée de conservation",
            "sous-traitants (ou) sous traitants",
          ],
    -     "score": 1,
    +     "score": 0,
          "slug": "pc",
        },
      ]

      63 |     url: "https://ressourcerie.fabrique.social.gouv.fr",
      64 |   });
    > 65 |   expect(output).toMatchSnapshot();
         |                  ^
      66 | });
      67 |

      at Object.toMatchSnapshot (__test__/analyseFile.test.js:65:18)

 › 5 snapshots failed.
Snapshot Summary
 › 5 snapshots failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       5 failed, 2 passed, 7 total
Snapshots:   5 failed, 1 passed, 6 total
Time:        217.142 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tristanrobert** [comment]
un `yarn test -u` a résolu l'incident.
